name: Pull Request Check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  builds:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"

      - name: Install Musl
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build
        run: |
          CGO_ENABLED=1 CC=musl-gcc go build --ldflags "-linkmode external -extldflags=-static -X main.VERSION=PR-$(git rev-parse --short HEAD)"

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            sate
