name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
        default: "vx.x.x"

jobs:
  builds:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"

      - name: Install Musl
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build
        run: |
          CGO_ENABLED=1 CC=musl-gcc go build --ldflags "-linkmode external -extldflags=-static -s -w -X main.VERSION=${{ inputs.version }}-$(git rev-parse --short HEAD)"

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            sate

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - builds
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: files
          path: files

      - name: Create Release and Upload Artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          name: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: true
          tag: ${{ inputs.version }}
          bodyFile: changelog.md
          artifacts: files/**/*
